osd_activate: fix osd umount on container stop
ceph/ceph-container pull request #1783
Opened 2021-01-14 00:33 UTC by guits

There's no need to have complexity to get the path of the current OSD.

By the way, at the moment this complexity leads to incorrect behavior:

```
-bash-4.2# docker exec ceph-osd-2 findmnt --nofsroot --noheadings --output SOURCE --submounts --target /var/lib/ceph/osd/
/dev/mapper/atomicos-root
/dev/sdb1
/dev/sda1
-bash-4.2# docker exec ceph-osd-2 df --output=target | grep '/var/lib/ceph/osd/'
/var/lib/ceph/osd/ceph-0
/var/lib/ceph/osd/ceph-2
-bash-4.2#
```

In the first method used in recent branches, it means we might try to umount
the root partition.
In the second method used in older branches we try to umount something
messed up:
```
2021-01-14 00:17:08  /opt/ceph-container/bin/entrypoint.sh: osd_disk_activate: Unmounting /var/lib/ceph/osd/ceph-0
/var/lib/ceph/osd/ceph-2

...

umount: /var/lib/ceph/osd/ceph-0
/var/lib/ceph/osd/ceph-2: mountpoint not found
++/opt/ceph-container/bin/osd_disk_activate.sh:92: sigterm_cleanup_post(): log 'osd_disk_activate: Failed to umount /var/lib/ceph/osd/ceph-0
/var/lib/ceph/osd/ceph-2'

...

++/opt/ceph-container/bin/common_functions.sh:13: log(): echo '2021-01-14 00:17:08  /opt/ceph-container/bin/entrypoint.sh: osd_disk_activate: Failed to umount /var/lib/ceph/osd/ceph-0
/var/lib/ceph/osd/ceph-2'

```
We can easily build and predict the path to umount since we have
`$CLUSTER` and `$OSD_ID` variable in the code of `osd_disk_activate.sh`

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

Description of your changes:

Which issue is resolved by this Pull Request:
Resolves #

Checklist:
- [ ] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.

2021-01-14 09:08 UTC, guits commented
jenkins test ceph_ansible-lvm_osds

2021-01-14 10:04 UTC, guits commented
jenkins test ceph_ansible-lvm_osds

2021-01-15 18:00 UTC, guits commented
jenkins test ceph_ansible-all_daemons

2021-01-15 18:10 UTC, guits commented
jenkins test ceph_ansible-collocation

2021-01-15 18:10 UTC, guits commented
jenkins test ceph_ansible-lvm_osds

2021-01-15 18:48 UTC, dsavineau commented on src/daemon/osd_scenarios/osd_disk_activate.sh
> +
shouldn't we do that before the ceph-volume simple activate ?

2021-01-15 20:15 UTC, dsavineau requested changes

2021-01-15 20:15 UTC, dsavineau commented on src/daemon/osd_scenarios/osd_volume_activate.sh
> +
this should be done only if OSD_VOLUME_TYPE==simple so probably need to integrate this statement after the osd_volume_simple call

2021-01-16 06:46 UTC, guits commented
jenkins test ceph_ansible-lvm_osds

2021-01-17 04:19 UTC, guits commented
jenkins test ceph_ansible-lvm_osds

2021-01-18 15:15 UTC, guits commented
jenkins test ceph_ansible-lvm_osds

2021-01-18 23:07 UTC, dsavineau commented
jenkins test ceph_ansible-lvm_osds

2021-01-28 19:49 UTC, dsavineau requested changes

2021-01-28 19:54 UTC, guits commented on src/daemon/osd_scenarios/osd_volume_activate.sh
> +    fi
```suggestion
```

2021-01-28 20:20 UTC, dsavineau commented on src/daemon/osd_scenarios/osd_volume_activate.sh
> +    fi
:+1:

2021-01-28 21:33 UTC, guits commented
jenkins test ceph_ansible-lvm_osds

2021-01-28 21:37 UTC, dsavineau approved these changes

2021-01-28 21:49 UTC, merged