gperftools: install from epel-testing for ceph octopus
ceph/ceph-container pull request #1817
Opened 2021-03-09 17:51 UTC by guits

This commit makes any build against el8 fetch gperftools from
epel-testing which provides 2.7 instead of epel which provides 2.8.

Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1933792
Related Tracker: https://tracker.ceph.com/issues/49618#note-5

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

2021-03-09 18:00 UTC, guits commented
@jdurgin FYI

2021-03-09 18:08 UTC, jdurgin approved these changes
looks good to me, can you confirm this results in gperftools 2.7?

2021-03-09 18:10 UTC, guits commented
```
Running transaction
  Preparing        :                                                        1/1 
  Installing       : libunwind-1.3.1-3.el8.x86_64                           1/2 
  Installing       : gperftools-libs-1:2.7-8.el8.x86_64                     2/2 
  Running scriptlet: gperftools-libs-1:2.7-8.el8.x86_64                     2/2 
  Verifying        : gperftools-libs-1:2.7-8.el8.x86_64                     1/2 
  Verifying        : libunwind-1.3.1-3.el8.x86_64                           2/2 
```

2021-03-09 18:35 UTC, dsavineau requested changes
Is it a temp workaround ?

I mean this look odd to have an older gperftools version in epel testing compared to the stable channel.

Are we going to rollback gperftools 2.7 on the epel 8 stable channel instead of 2.8 ? Because I'm a little bit worried if a newer release is pushed to epel 8 testing (like 2.9) which could be really bad.

@ktdreyer do you have more visibility on this on the long term.

2021-03-09 18:35 UTC, dsavineau commented on ceph-releases/ALL/centos/8/daemon-base/__GPERFTOOLS_LIBS__
> +--enablerepo='epel-testing' gperftools-libs
extra space at the end of the line

2021-03-09 18:39 UTC, dsavineau commented
@guits do we really need this in stable-4.0 ?

Because Nautilus is built on CentOS 7 which uses gperftools 2.6 from the base repository (not epel)

2021-03-09 18:40 UTC, jdurgin commented
Yes this is temporary - to be able to build new releases without tcmalloc 2.8, which unfortunately was included in the 15.2.9 container. We're in the midst of preparing a nautilus release, and will likely do an octopus release to fix this next week.

2021-03-09 18:43 UTC, dsavineau commented
ack, so we just need a reminder for removing this once 2.7 is pushed back to epel stable.

> We're in the midst of preparing a nautilus release

Note that the next nautilus release (14.2.17) won't be affected since the container is based on CentOS 7 and not 8

2021-03-09 18:48 UTC, jdurgin commented
great, thanks for confirming nautilus won't be affected

2021-03-09 19:53 UTC, guits commented
@dsavineau I'm unsure whether this is relevant to backport this patch in stable-4.0 I was just thinking if someone wants to build against el8/ceph@nautilus he would hit the bug, feel free to remove the 'backport stable-4.0' label if you estimate this isn't worthwhile. Thanks!

2021-03-09 20:26 UTC, dsavineau approved these changes

2021-03-09 20:27 UTC, merged

2021-04-06 19:08 UTC, ktdreyer commented
We can revert this now

2021-04-06 20:10 UTC, dsavineau commented
> We can revert this now

This has been already reverted in #1831