common: set env var CEPH_CONTAINERIZED
ceph/ceph-container pull request #1969
Opened 2021-12-01 14:49 UTC by guits

So any tool can detect whether it is actually running
from within a container.

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

2021-12-01 14:51 UTC, guits commented
@leseb FYI

2021-12-01 14:58 UTC, sebastian-philipp commented
relates to 

https://github.com/ceph/ceph/blob/a67d1cf2a7a4031609a5d37baa01ffdfef80e993/src/common/hostname.cc#L24

https://github.com/ceph/ceph/blob/c65798342a5bcc66b8c3c3d96132fc68d893843a/src/msg/Messenger.cc#L24

2021-12-01 15:20 UTC, guits commented
jenkins test ceph_ansible-lvm_osds

2021-12-01 16:05 UTC, dsavineau requested changes

2021-12-01 16:05 UTC, dsavineau commented on tests/setup.yml
> +      loop: "{{ insecure_registry_config | dict2item }}"
```suggestion
      loop: "{{ insecure_registry_config | dict2items }}"
```

2021-12-02 08:17 UTC, leseb approved these changes

2021-12-02 09:16 UTC, merged