Remove ceph-iscsi and tcmu-runner from ubi9
ceph/ceph-container pull request #2029
Opened 2022-07-07 17:21 UTC by bigjust

neither are supported on RHEL9

Signed-off-by: Justin Caratzas <jcaratza@redhat.com>

Description of your changes:

Which issue is resolved by this Pull Request:
Resolves #

Checklist:
- [ ] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.

2022-07-07 18:00 UTC, idryomov requested changes
> neither are supported on RHEL9

I'm not sure I'm following...  Is ubi9 image specific to RHEL9?  What about CentOS 9 Stream?

2022-07-07 18:01 UTC, ktdreyer approved these changes

2022-07-07 18:01 UTC, ktdreyer commented
We're dropping these packages, right? They're no longer supported?

2022-07-08 16:21 UTC, ktdreyer commented
This change only applies to RHCS 6

2022-07-11 15:48 UTC, idryomov approved these changes
Ack from the RBD perspective (based on Ken's clarification)

2022-07-12 12:29 UTC, guits approved these changes

2022-07-12 12:29 UTC, guits commented
failures are unrelated

2022-07-12 23:18 UTC, guits commented
jenkins test ceph_ansible-collocation

2022-07-12 23:18 UTC, guits commented
jenkins test ceph_ansible-lvm_osds

2022-07-12 23:23 UTC, merged