ubi9: change text to reflect rhcs 5 -> 6
ceph/ceph-container pull request #2030
Opened 2022-07-07 17:24 UTC by bigjust

Signed-off-by: Justin Caratzas <jcaratza@redhat.com>

Description of your changes:

Which issue is resolved by this Pull Request:
Resolves #

Checklist:
- [ ] Documentation has been updated, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.

2022-07-07 18:02 UTC, ktdreyer commented
Want to edit `contrib/rhcs.md` as well?

2022-07-12 12:36 UTC, guits approved these changes

2022-07-12 12:40 UTC, guits requested changes

2022-07-12 12:40 UTC, guits commented on contrib/compose-rhcs.sh
> +COMPOSED_DIR=$STAGING_DIRcomposed
```suggestion
COMPOSED_DIR="${STAGING_DIR}"composed
```

2022-07-12 23:15 UTC, guits commented
jenkins test ceph_ansible-all_daemons

2022-07-12 23:16 UTC, guits commented
jenkins test ceph_ansible-collocation

2022-07-12 23:16 UTC, guits commented
jenkins test ceph_ansible-lvm_osds

2022-07-12 23:18 UTC, guits approved these changes

2022-07-12 23:18 UTC, merged