get mem on cgroupsv2
ceph/ceph-container pull request #2119
Opened 2023-06-07 13:36 UTC by KannarFr

Description of your changes:

Fixes: #2118

2023-06-08 14:46 UTC, KannarFr commented
I checked the failing test but got

```


Identified problems
--
  | No identified problemNo problems were identified. If you know why this problem occurred, please add a suitable Cause for it.
```

Shall I run a bash linter or something?

2023-07-31 13:55 UTC, guits commented
jenkins test sloppy bash

2023-07-31 13:56 UTC, guits commented
jenkins lint

2023-07-31 13:57 UTC, guits commented
```

In /common_functions.sh line 525:
  if grep -q cgroup2 /proc/filesystems; then
  ^-- SC1009 (info): The mentioned syntax error was in this if expression.


In /common_functions.sh line 529:
  elif
  ^-- SC1049 (error): Did you forget the 'then' for this 'elif'?
  ^-- SC1073 (error): Couldn't parse this elif clause. Fix to allow more checks.


In /common_functions.sh line 533:
  fi
    ^-- SC1072 (error): Unexpected keyword/token. Fix any mentioned problems and try again.
```

2023-08-01 08:21 UTC, guits commented on src/daemon/common_functions.sh
> +    memory_current_usage_in_bytes_file="/sys/fs/cgroup/memory.current"
@KannarFr 

```console
[root@7f9056067200 /]# grep cgroup2 /proc/filesystems
nodev	cgroup2
[root@7f9056067200 /]# ls /sys/fs/cgroup/memory.max
ls: cannot access '/sys/fs/cgroup/memory.max': No such file or directory
[root@7f9056067200 /]# ls /sys/fs/cgroup/memory.current
ls: cannot access '/sys/fs/cgroup/memory.current': No such file or directory
[root@7f9056067200 /]#
```

from the documentation [1] :
>  memory.usage_in_bytes		 # show current usage for memory
 memory.limit_in_bytes		 # set/show limit of memory usage


did you mean `/sys/fs/cgroup/memory/memory.limit_in_bytes`  `/sys/fs/cgroup/memory/memory.usage_in_bytes` ?

2023-08-01 08:25 UTC, guits requested changes

2023-08-01 08:48 UTC, guits commented on src/daemon/common_functions.sh
> +  if grep -q cgroup2 /proc/filesystems; then
shouldn't it be checked from `/proc/mounts` instead?

```console
# grep cgroup2 /proc/mounts
cgroup2 /sys/fs/cgroup cgroup2 rw,seclabel,nosuid,nodev,noexec,relatime,nsdelegate 0 0
#
```

2023-08-01 12:04 UTC, guits commented on src/daemon/common_functions.sh
> +    memory_current_usage_in_bytes_file="/sys/fs/cgroup/memory.current"
@KannarFr forget about this comment, I think I got confused.

2023-08-01 12:42 UTC, guits requested changes

2023-08-01 12:42 UTC, guits commented on src/daemon/common_functions.sh
> +    memory_current_usage=$(cat memory_current_usage_in_bytes_file)
```suggestion
    memory_current_usage=$(cat $memory_current_usage_in_bytes_file)
```

2023-08-01 12:45 UTC, guits reviewed
not related to this patch but if you want to address the warning `SC2071` L124 you can apply this small change:

```diff
diff --git a/src/daemon/common_functions.sh b/src/daemon/common_functions.sh
index 1b679c6c..9e99046f 100755
--- a/src/daemon/common_functions.sh
+++ b/src/daemon/common_functions.sh
@@ -121,7 +121,7 @@ function dev_part {
       if [[ $(readlink -f "$option") == "$desired_partition" ]]; then
         local optprefixlen
         optprefixlen=$(prefix_length "$option" "$osd_device")
-        if [[ $optprefixlen > $pfxlen ]]; then
+        if [[ $optprefixlen -gt $pfxlen ]]; then
           link=$option
           pfxlen=$optprefixlen
         fi
```

2023-08-01 12:45 UTC, guits requested changes
@KannarFr you need to add a sign off to your commit message

thanks!

2023-08-01 13:24 UTC, KannarFr commented
@guits thanks for the hints. I applied all of them. I also sign off it.

2023-08-01 13:55 UTC, guits commented
@KannarFr Could you squash the first 3 commits? I think you should have only 2 commits in this PR.

`get mem on cgroupsv2` and `apply unrelated lint fix`

Thanks!

2023-08-01 14:02 UTC, KannarFr commented
@guits Damn I thought github will do it by itself. Done.

2023-08-03 11:29 UTC, guits approved these changes

2023-08-03 14:18 UTC, guits commented
failure in `container / arm64` is unrelated to this patch

2023-08-07 08:22 UTC, merged

2023-08-07 09:41 UTC, KannarFr commented
@guits can you make a release with this patch? :)

2023-08-08 11:04 UTC, guits commented
@KannarFr which release are you looking for?

2023-08-08 11:52 UTC, KannarFr commented
`ceph/daemon`