deprecate repository
ceph/ceph-container pull request #2256
Opened 2024-12-03 17:29 UTC by ktdreyer

Remove all the files in the repository and point users at the new `Containerfile` location.

2024-12-04 08:11 UTC, guits approved these changes

2024-12-04 13:41 UTC, guits commented
@ktdreyer I wonder if removing everything might be a bit too "aggressive" for now. Shouldn't we just update the `README.md` to inform people that the repository is deprecated and redirect them to the `Containerfile` location?

2024-12-04 19:32 UTC, ktdreyer commented
The files will still be in the Git history. Removing the files makes it clear to users and contributors that developers are focused on the new area.

2024-12-04 19:44 UTC, travisn commented
Why not just archive the repo so it's readonly? And how will they know where to find new development if the readme is even empty?

2024-12-04 19:55 UTC, guits commented
> And how will they know where to find new development if the readme is even empty?

Correct. Although I still think that removing everything is a bit aggressive, I would at least leave a comment in README.md to let users know what's happening.

2024-12-04 21:00 UTC, ktdreyer commented
Whoops, sorry! I wrote a new README but I forgot to push it in this PR. I've amended and re-pushed. It can be a little difficult to read in this large GitHub diff, so I'll paste the README contents here:

--------

`Containerfile` has moved
-------------------------

This `ceph-container` GitHub repository is deprecated and read-only. **The Ceph developers have moved all development to the `Containerfile` in the primary `ceph` GitHub repository:**

* `main`: https://github.com/ceph/ceph/blob/main/container/Containerfile

Older releases:

* `squid`: https://github.com/ceph/ceph/blob/squid/container/Containerfile
* `reef`: https://github.com/ceph/ceph/blob/squid/container/Containerfile
* `quincy`: https://github.com/ceph/ceph/blob/quincy/container/Containerfile

Please make future contributions to these locations.


History
-------

This repository originally held the first experiments of putting Ceph into container images. Later on, this repository held a variety of operating systems and versions in file snippets with a templating system. We have simplified this to a single flat `Containerfile`, one per Ceph release.

2024-12-05 07:41 UTC, guits approved these changes

2024-12-05 07:42 UTC, guits requested changes

2024-12-05 07:42 UTC, guits commented on README.md
> +* `reef`: https://github.com/ceph/ceph/blob/squid/container/Containerfile
```suggestion
* `reef`: https://github.com/ceph/ceph/blob/reef/container/Containerfile
```

2024-12-06 14:09 UTC, ktdreyer commented on README.md
> +* `reef`: https://github.com/ceph/ceph/blob/squid/container/Containerfile
Thank you for catching this. I've amended and re-pushed.

2024-12-08 11:55 UTC, guits approved these changes

2024-12-09 15:12 UTC, ktdreyer commented
@dmick , is this ready to merge now?

2024-12-09 17:05 UTC, dmick commented
We should disable/delete the Jenkins jobs that use it first, probably.
Working on that and the change to the third release "ceph" job to add the
new container build

On Mon, Dec 9, 2024, 7:12 AM Ken Dreyer ***@***.***> wrote:

> @dmick <https://github.com/dmick> , is this ready to merge now?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ceph/ceph-container/pull/2256#issuecomment-2528289421>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAKJYENEDTGVSS7H7APRG3D2EWXPLAVCNFSM6AAAAABS6JYKZKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMRYGI4DSNBSGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-12-12 14:44 UTC, ktdreyer commented
Now that https://github.com/ceph/ceph-build/pull/2305 is done, @dmick is this read to merge?

2024-12-12 18:29 UTC, dmick commented
I think so.  I think https://github.com/ceph/ceph/pull/60936 is too if I could get a review 😄

2024-12-12 18:29 UTC, dmick approved these changes

2024-12-12 18:30 UTC, merged